Add OPA UA protocol flow
CESARBR/knot-virtualthing pull request #31
Opened 2022-07-18 23:03 UTC by rtorresmatheus

Add OPC UA protocol by doing the following changes:

- Add driver flow for OPC UA;
- Add driver files for OPC UA;
- Change parameters to accept OPC UA configuration;
- Add iface-opc-ua files;
- Add read flow for OPC UA;
- Add connect flow for OPC UA;
- Add disconnect flow for OPC UA.

2022-07-19 19:30 UTC, luisfelipemisi reviewed
Very good, clean code. I was just confused about the name of a variable "retval".

2022-07-19 19:30 UTC, luisfelipemisil commented on src/iface-opc-ua.c
> +	retval = UA_Client_connect(opc_ua_client,
"retval" - What does this variable name mean?

2022-07-19 19:30 UTC, luisfelipemisil commented on src/iface-opc-ua.c
> +	retval = UA_ClientConfig_setDefault(UA_Client_getConfig(opc_ua_client));
"retval" - What does this variable name mean?

2022-07-20 22:23 UTC, AntonioJanael approved these changes
Very clean and good code.

2022-07-25 17:31 UTC, vitbaq requested changes
Great patch. I made some suggestions, feel free to comment.

2022-07-25 17:31 UTC, vitbaq commented on confs/device.conf
>  # KNoT Virtual Thing supports Modbus RTU, Modbus TCP and Ethernet/IP
`# KNoT Virtual Thing supports Modbus RTU, Modbus TCP, Ethernet/IP and OPC UA`

2022-07-25 17:31 UTC, vitbaq commented on confs/device.conf
> +# DRIVER_SECURITY = FALSE
I think that you can remove this line. The explanation on line 43 it is enough to understand.

2022-07-25 17:31 UTC, vitbaq commented on confs/device.conf
> +# DeviceProtocolType = OPC_UA
Isn't this file getting too complex? It is an example for four different types of protocols/devices.
An alternative is to create a file for each:
```
device-modbus.conf.example
device-ethernet-ip.conf.example
device-opc-ua.conf.example
```
and recommends that to use it, just make a copy and remove the .example.

2022-07-25 17:31 UTC, vitbaq commented on src/properties.c
> +	namespace_aux = storage_read_key_string(fd, group_id,
Is this function (set_data_properties) called only when it is opc UA?
if not, if the device is ethernet-ip will it work? Because it will have attributes that ethernet-ip does not need.

2022-07-25 17:31 UTC, vitbaq commented on src/properties.c
> +	login = storage_read_key_string(fd, THING_GROUP,
Same question here.

Is this function (set_driver_properties) called only when it is opc UA?
if not, if the device is ethernet-ip will it work? Because it will have attributes that ethernet-ip does not need.

2022-07-25 17:31 UTC, vitbaq commented on Makefile.am
> +		@OPEN62541_CFLAGS@ @MODBUS_CFLAGS@
Where is `@PLCTAG_CFLAGS@`?

2022-07-25 17:31 UTC, vitbaq commented on src/iface-opc-ua.c
> +	retval = UA_Client_connect(opc_ua_client,
return value. It is a common way of abbreviating.

Pls, @rtorresmatheus, check if it is the pattern of the file.

2022-07-25 17:31 UTC, vitbaq commented on src/driver.c
> +	else if (!strcmp(protocol, "OPC_UA"))
Fix this on the first commit

2022-07-25 17:31 UTC, vitbaq commented on src/conf-device.h
> +	int namespace;
Fix this on the first commit

2022-07-25 17:31 UTC, vitbaq commented on src/iface-opc-ua.c
> +	UA_StatusCode retval = 0;
What is 0? If its possible use the string instead of the int, like `UA_STATUSCODE_GOOD`

2022-07-25 17:31 UTC, vitbaq commented on src/properties.c
> +	rc = storage_read_key_int(fd, group_id, DATA_NAME_SPACE_INDEX,
Fix this on the first commit

2022-07-25 17:31 UTC, vitbaq commented on src/iface-opc-ua.c
> +	UA_StatusCode retval = 0;
If you are going to change this, look at the other occurrences as well.

2022-08-05 17:13 UTC, rtorresmatheus commented on confs/device.conf
> +# DeviceProtocolType = OPC_UA
Yes, It's very complex, but we'll development this alternative in another PR.

2022-08-19 17:06 UTC, vitbaq approved these changes

2022-08-19 17:07 UTC, merged