Add opcua cript
CESARBR/knot-virtualthing pull request #32
Opened 2022-08-05 21:18 UTC by rtorresmatheus

Add security of OPC UA protocol by doing the following changes:

- Add information about security for OPC UA;
- Change parameters to accept OPC UA security configuration.

2022-08-22 12:24 UTC, AntonioJanael requested changes
Great job! The code is clean and concise. Very interesting.

2022-08-22 12:24 UTC, AntonioJanael commented on src/conf-device.h
> +#define DRIVER_MAX_SECURITY_LEN			256
Where in the code do we use this macro?

2022-08-22 12:24 UTC, AntonioJanael commented on src/conf-device.h
> +#define DRIVER_MAX_NAMESPACE_LEN		25
Where in the code do we use this macro?

2022-08-22 12:24 UTC, AntonioJanael commented on src/conf-parameters.h
> +#define DRIVER_PATH_PRIVATEKEY		"DevicePathPrivateKey"
What do you think of DRIVER_PATH_PRIVATE_KEY?

2022-08-22 12:24 UTC, AntonioJanael commented on src/iface-opc-ua.c
> + * Copyright (c) 2020, CESAR. All rights reserved.
2020 -> 2022?

2022-08-22 12:24 UTC, AntonioJanael commented on src/iface-opc-ua.c
> +#define RECONNECT_TIMEOUT 5
Seconds, milliseconds, hours? Would it be worth including the time unit in the macro name? For example, RECONNECT_TIMEOUT_IN_SECONDS = 5.

2022-08-22 12:24 UTC, AntonioJanael commented on src/iface-opc-ua.c
> +#define STRING_EMPTY 0
What do you think of STRING_EMPTY_LEN? So it will be clearer that this macro contains the length of an empty string.

2022-08-22 12:24 UTC, AntonioJanael commented on src/iface-opc-ua.c
> +		      (uint32_t)identifier[3];
What do you think about extracting this snippet between lines 104 and 107 to a function? We can pass the "identifier" as an argument of the function and receive the return of the operation.

2022-08-22 12:24 UTC, AntonioJanael commented on src/iface-opc-ua.c
> +		break;
The need for these conditionals is clear. However, there are too many nested conditionals. Would it be worth extracting the snippets from the KNOT_VALUE_TYPE_BOOL, KNOT_VALUE_TYPE_INT and KNOT_VALUE_TYPE_UIN cases to functions?

2022-08-22 12:24 UTC, AntonioJanael commented on src/iface-opc-ua.c
> +	if (strlen(thing_opc_ua.driver_login) != STRING_EMPTY) {
What happens if the password is empty? Shouldn't we also check if the password is different from an empty string?

2022-08-22 12:24 UTC, AntonioJanael commented on src/iface-opc-ua.c
> +	if (strlen(thing_opc_ua.driver_login) != STRING_EMPTY) {
The connection is made with or without authentication depending on the configuration, right? If so, what do you think of making the intention of this code snippet a little clearer? For example, creating a constant that identifies whether the connection is authenticated or not.

```
const int is_authenticated_connection = (strlen(thing_opc_ua.driver_login) != STRING_EMPTY) ? 1 : 0;

if (is_authenticated_connection){
…
} else {
}
```

2022-08-22 12:24 UTC, AntonioJanael commented on src/iface-opc-ua.c
> +		goto retry;
Is the “goto” statement safe in this context?

2022-08-24 20:00 UTC, AntonioJanael approved these changes

2022-08-24 20:02 UTC, luisfelipemisi approved these changes

2022-08-25 19:17 UTC, merged